### ISSUE TITLE
Unclear error message when posting news

### ISSUE THREAD

**Issue by kirayatail** [cthit/chalmersit-rails#66]
Posting multi-language news with attachment results in unhelpful error message: "Please review the problems below" without any information below.

**Comment by Vilddjur** [comment]
This particular case was an issue where the server couldn't properly localize its slugs, while this might be good for the user to see in order to better give the developers an idea of what went wrong I am having a hard time seeing how we could display these messages for the user while still not displaying regular error messages (such as too short title which is displayed beneath the title in a pretty box) twice.

**Comment by Vilddjur** [comment]
I am closing this since we have fixed the problems where slugs were validated incorrectly
